### ISSUE TITLE
Blog Optimize Roadmap

### ISSUE THREAD

**Issue by PerfectPan** [PerfectPan/blog#30]
### P0

- [x] Refactor using waku
- [x] Blog List style optimization
- [x] Blog Post Page style optimization
- [x] React-markdown switch to raw mdx runtime
- [x] Github Icon
- [x] RSS
- [x] Merge refactor branch into master branch

### P1

- [x] Code format / Code Lint https://github.com/PerfectPan/blog/pull/36
- [x] DarkMode https://github.com/PerfectPan/blog/pull/34
- [ ] Code block support paste
- [x] Basic CI https://github.com/PerfectPan/blog/pull/37
- [ ] Search
- [ ] Pagination

### P2

- [ ] Blog Info use Jotai to manage
- [ ] Can image not be stored in the `public/images` folder?
- [ ] StartTransition
- [ ] PWA support
- [ ] RSS content support
- [ ] Remove next-mdx-remote?
